name: Github Actions Hello World Demo

on: [pull_request]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: printing hello
        run: |
          echo "Hello World"
      - name: Running a basic python application
        run: |
          pip install -r requirements.txt
          python ci.py
