on: push

jobs:
  secret_job:
    runs-on: ubuntu-latest
    steps:
      - name: Creating a secret and accessing it as an environment variable
        env:
          MY_VAR: $ {{secrets.MY_SECRET}}
        run: echo $MY_VAR
      - name: Printing the length of the secret
        shell: python
        run: |
          import os
          print(os.getenv("MY_VAR"))
          print(len(os.getenv("MY_VAR")))
